import type { Metadata } from "next";
import "./globals.css";
import "../styles/antd-overrides.css";
import { AuthProvider } from "@/contexts/AuthContext";
import AntdConfigProvider from "@/lib/antd-config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <AntdConfigProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </AntdConfigProvider>
      </body>
    </html>
  );
}
